INC=-I../../../Hausaufgaben/Hausaufgabe_2/A1/ \
	 -I../../../Hausaufgaben/Hausaufgabe_2/A2/

SRC=main.cpp Spieler.cpp PacMan.cpp Labyrinth.cpp \
	 MyString.cpp Position.cpp

default: 
	g++ -g -o main $(SRC) --std=c++11 $(INC) -lncurses

